### ISSUE TITLE
Adding a search string with a tag already selected doesn't narrow down results

### ISSUE THREAD

**Issue by sglangevin** [calblueprint/worldreader#229]
When I am searching, if I add a tag and then enter a search term, the search results remain the same. If I add a search term and then a tag, I get the expected result (library narrowed down by search term and also by the tag). Generally, if I search for one search term after another, the results don't seem to update. For example, I searched for mathematics then deleted that and searched for history. This produced entirely different results than when I just searched for history.

**Comment by varunrau** [comment]
This should be fixed in #237.

**Comment by varunrau** [comment]
The fix should now be on extranet.worldreader.org.
