### ISSUE TITLE
Brainstorm how to make tag search more intuitive

### ISSUE THREAD

**Issue by varunrau** [calblueprint/worldreader#257]
Perhaps using a tutorial or an informational modal?

I'm worried that uses won't get it.

**Comment by varunrau** [comment]
Worldreader was interested in adding an informational modal that could demonstrate how tag search works and a list of all the available tags.

**Comment by varunrau** [comment]
Perhaps a ? mark on the right side of the tags search bar?

**Comment by echiou** [comment]
@varunrau I like the idea of a small question mark that pops a modal up explaining how the tags work.
I'll look into that.
