### ISSUE TITLE
Add validation header to book list page

### ISSUE THREAD

**Issue by varunrau** [calblueprint/worldreader#310]
This issue is referring to the four numbers at the top of the table.

When the african number and the international number are not equal, the text should be red.
[Book List Composition Page original.pdf | uploaded via ZenHub](https://files.zenhub.io/552467d9ee0abd400e1dde7a)

**Comment by wt24** [comment]
African books: Book.publisher.free == "paid"

**Comment by wt24** [comment]
BookType = "international" or "african"
